spring:
  application:
    name: cards
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka