server:
  port: 8000
spring:
  application:
    name: gateway
#This will enable cloud gateway to fetch all the registry form discovery service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
# http://localhost:8000/actuator/gateway/routes
#check all the exposed routes

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      microservice:
        gateway: DEBUG
#Configure info endpoints
info:
  app:
    name: gateway
    description: This is the APIGATEWAY server
    version: 0.0.1
#enable  info endpoints
management:
  info:
    env:
      enabled: true
#For all Actuator end points
  endpoints:
    web:
      exposure:
        include: "*"

