server:
  port: 8000
spring:
  application:
    name: gateway
#percentage of request sent ot zipkin
  sleuth:
    sampler:
      probability: 1
#zipkin base url where zipkin is running
  zipkin:
    base-url: http://localhost:9411/
##Rabbitmq Configuration
#    sender:
#      type: rabbit
#    rabbitmq:
#      queue: zipkin
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


#This will enable cloud gateway to fetch all the registry form discovery service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
# http://localhost:8000/actuator/gateway/routes
#check all the exposed routes

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#Configure info endpoints
info:
  app:
    name: gateway
    description: This is the APIGATEWAY server
    version: 0.0.1
#enable  info endpoints
management:
  info:
    env:
      enabled: true
#For all Actuator end points
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"



