accounts:
  msg: Welcome to my banking application
  build-version: 3
  mailDetails:
    hostName: default-account@gmail.com
    port: 9000
    from: default-account@gmail.com
    subject: Your acccount is opened
  activeBranches:
    - Mumbai
    - London
    - Washington
