spring:
  application:
    name: configserver
# To read the configuration from classpath.
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/naresh546nk/banking-config.git
          clone-on-start: true
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8071