version: '3.8'
services:
  accounts:
    image: naresh546/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - banking
  loans:
    image: naresh546/loan:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - banking
  cards:
    image: naresh546/card:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - banking
networks:
  banking: